apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wxdsc0i00-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9b0c2477ed.3som.p3.openshiftapps.com/rhtap/rhtap-qe:8efcef703d0c761167a9c7f136aa091644ca65a4@sha256:2c978141eaef94ef1521ed69f4477eb72d289d8212fb02fc700ca64619a25c58
          name: container-image
