apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wxdsc0i00-python
  janus-idp.io/tekton: wxdsc0i00-python
  backstage.io/kubernetes-id: wxdsc0i00-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wxdsc0i00-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
